### ISSUE TITLE
Update Native SDK versions

### ISSUE THREAD

**Issue by dnikolaev** [marpies/onesignal-ane#1]
Hi @marpies,

Native SDK was updated by OneSignal. It's important to keep ANE up-to-date. 

https://github.com/OneSignal/OneSignal-iOS-SDK
https://github.com/OneSignal/OneSignal-Android-SDK

**Comment by jkasten2** [comment]
@marpies Let me know if you have any questions on updating to the OneSignal 2.0 and 3.0 SDKs. See our notes of our changes below if you haven't seen them already.

https://documentation.onesignal.com/docs/upgrading-to-sdk-30
https://documentation.onesignal.com/docs/upgrading-to-sdk-20

**Comment by marpies** [comment]
Thanks @jkasten2,

I'll have a look at it shortly.
