### ISSUE TITLE
iOS 10, Rich Media Attachments Doesn't Work

### ISSUE THREAD

**Issue by dnikolaev** [marpies/onesignal-ane#10]
Hi @marpies,

I've tried to send push via OneSignal with rich media attachment (image). Push notification appear only at all iOS 9.x.x devices (without image). It isn't showed at iOS 10.x.x completely. I've used several images. All the same.

<img width="569" alt="onesignal-ios-config" src="https://cloud.githubusercontent.com/assets/5558855/22920556/a337a3e6-f2a6-11e6-8a22-04d464d58790.png">

Please fix this issue.

Regards,
Dmitrii

**Comment by jkasten2** [comment]
Notifications with iOS 10 attachments or action buttons have some extra requirements. See the [Notifications with action buttons or iOS 10 media not displaying](https://documentation.onesignal.com/docs/troubleshooting-ios#section-notifications-with-action-buttons-or-ios-10-media-not-displaying) section in our troubleshooting guide.

Thanks.

**Comment by marpies** [comment]
Hi @dnikolaev,

Did you manage to solve the issue on your side or do you think there is a problem with the ANE?

**Comment by dnikolaev** [comment]
I didn't have a chance to look at this issue. I'll check it tomorrow.

**Comment by dnikolaev** [comment]
Hi @marpies,

I've checked extra requirements. Notifications with attachments isn't worked.

Have you tested this feature?

Regards,
Dmitrii

**Comment by marpies** [comment]
Hi @dnikolaev,

Thanks for reporting back. I'll take a look at it and let you know.

**Comment by marpies** [comment]
Hi @dnikolaev,

I tried sending media notification but indeed it never shows up. If I send the same notification with the 'media' field empty then it shows up just fine. For every media notification I send I see the following log message on the receiving device:

```
SpringBoard(UserNotificationsServer)[57] <Error>: Ignoring notification with no content (com.marpies.demo.onesignal): 2FB0-272E
```

@jkasten2 Any idea on what could be causing this and how to resolve it?

**Comment by dnikolaev** [comment]
Have you used last iOS SDK at ANE?

**Comment by jkasten2** [comment]
@marpies That entry is to be expected. These kind of notifications don't have a body, they are silent notifications using `content-available`. From the event they display a local notification. Search for `UserNotificationsServer` in the log. You should see entries below it like the following.
```Swift
Mar  2 11:37:24 OneSignal-iPhone6s16GB SpringBoard(UserNotificationsServer)[60] <Notice>: [com.onesignal.example] Load last local notification fire date: 2017-03-02 11:37:23.624 -0800
Mar  2 11:37:24 OneSignal-iPhone6s16GB SpringBoard(UserNotificationsServer)[60] <Notice>: [com.onesignal.example] Find next notification with current trigger date after last fire date 2017-03-02 11:37:23.624 -0800
```

**Comment by marpies** [comment]
@jkasten2 I see, thanks for the input.

@dnikolaev Good news is I managed to find the issue, not so good news is that it's not supported in AIR 24 by default and requires a couple of additional steps to make it work. There should be no steps required once AIR 25 is released. I'll create a separate branch with instructions on how to make this work and let you know when it's available.

![notification](https://cloud.githubusercontent.com/assets/6077555/23529194/f1b91a42-ff9c-11e6-8ae7-314f5d86b91d.png)

**Comment by dnikolaev** [comment]
We use AIR 22 to build iOS (Because of this bug https://tracker.adobe.com/#/view/AIR-4198266). Please provide instructions for AIR 22 too. Thank you so much in advance.

**Comment by marpies** [comment]
@dnikolaev I've added the [new branch](https://github.com/marpies/onesignal-ane/tree/ios-10-media). You can read the additional steps on you need to do on the [README page](https://github.com/marpies/onesignal-ane/tree/ios-10-media#packaging-your-app).

**Comment by dnikolaev** [comment]
@marpies I'll try it. Thanks.
