### ISSUE TITLE
Android init but not registering.

### ISSUE THREAD

**Issue by leossmith** [marpies/onesignal-ane#12]
I am trying the ANE on one of my projects and although it initialiazes as expected, no user is registered. I have setted auto-registration to true and also tried .register() onstart.

I am testing on Android 7 and Android 6 (oneplus3 and oneplus1). 

I am using google play services 10 and the latest androidsupport (all from myflashlabs as i use several other anes too).

Any idea what could be wrong?

Thank you.

**Comment by marpies** [comment]
Not sure what could be wrong. Is your `idsAvailable` callback triggered after you call `register` and do you receive a push token?

I'll have to try it out using Google Play Services 10 to see what's really going on.

**Comment by jkasten2** [comment]
@leossmith @marpies I have been testing our native OneSignal Android SDK with Google Play services 10 (both device and library versions) without any issues.

The device should show up on the OneSignal dashboard even if you don't have it at all. However it will just show up as no subscribed if this is the case.

I recommend making sure your app_id is correct, OneSignal is being called in your code by adding logging, and check the logcat for any additional errors / warnings.

**Comment by leossmith** [comment]
So after further investigation, it looks like there was a conflict with another ANE. After clearing my manifest, everything works as expected. 

Thank you for the help.
