### ISSUE TITLE
Add Notification Title

### ISSUE THREAD

**Issue by leossmith** [marpies/onesignal-ane#13]
Please add Title in the notification payload.

Thank you.

**Comment by marpies** [comment]
The title should be part of the `additionalData` object:

```as3
function onNotificationReceived( notification:OneSignalNotification ):void {
    if( "title" in notification.additionalData ) {
        trace(notification.additionalData.title);
    }
}
```

**Comment by leossmith** [comment]
Oh, I didn't know. Thank you, this looks like this is very flexible with data :)

**Comment by marpies** [comment]
You can post additional data via the OneSignal console and it will be part of the `additionalData` object:

![data](https://cloud.githubusercontent.com/assets/6077555/23529772/225eca3c-ff9f-11e6-97b9-23b1c1368a74.png)

```as3
function onNotificationReceived( notification:OneSignalNotification ):void {
    trace(notification.additionalData.extra); // Hello World
}
```
