### ISSUE TITLE
Flex Error in Packaging the application

### ISSUE THREAD

**Issue by romeoobane** [marpies/onesignal-ane#15]
I managed to rebuild the ANE after I've updated the icons for Android, but when I add the extension to my project and export for iOS, I encounter this error:

![screen shot 2017-03-16 at 12 07 58 pm](https://cloud.githubusercontent.com/assets/12105534/23983768/de83beb4-0a50-11e7-9498-9458b88f14ff.png)

So far no issue when adding the extension and exporting for Android. 

Kindly advice, thank you.

**Comment by marpies** [comment]
It looks you are using the version from ios-10-media branch. See the [extra requirements](https://github.com/marpies/onesignal-ane/tree/ios-10-media#packaging-your-app) for packaging your app with this version or use the master branch.
