### ISSUE TITLE
send notification from device.

### ISSUE THREAD

**Issue by benkhachouch** [marpies/onesignal-ane#17]
Is it really possible to send notification from device?
Thanks.

**Comment by marpies** [comment]
Yes.

[OneSignal.postNotification(...)](https://github.com/marpies/onesignal-ane/blob/master/actionscript/src/com/marpies/ane/onesignal/OneSignal.as#L259-L300)
[OneSignal documentation](https://documentation.onesignal.com/reference#page-create-notification)

**Comment by benkhachouch** [comment]
When i use  OneSignal.postNotification(...)  I get this error:

Please include a case-sensitive header of Authorization: Basic <YOUR-REST-API-KEY-HERE> with a valid REST API key.

what are minimal parameters to include?

Thanks

**Comment by benkhachouch** [comment]
My code:

	var para:Object=new Object;
			para.app_id="1374654d-c1c0-46f5-bff6-9a910a91d53a"
			para.included_segments= ["Active Users", "Inactive Users"]
			para.contents={"en": "English Message", "es": "Spanish Message"};
			para.headings={"en": "English Title", "es": "Spanish Title"}
				para.subtitle={"en": "English Subtitle", "es": "Spanish Subtitle"}
				
		    OneSignal.postNotification(para,reponse)
			
		}
		private function reponse( successResponse:Object, errorResponse:Object ):void {
			if( successResponse != null ) {
				trace("success")
			} else if( errorResponse != null ) {
				trace(errorResponse+"error")
				for(var r in errorResponse){
					trace(errorResponse[r])
				}
			}
		}

**Comment by marpies** [comment]
You can only use `include_player_ids` as a targeting parameter from your app. See the [documentation](https://github.com/marpies/onesignal-ane/blob/master/actionscript/src/com/marpies/ane/onesignal/OneSignal.as#L263-L265).

**Comment by benkhachouch** [comment]
Thanks☺

2017-03-26 16:05 GMT+02:00 marpies <notifications@github.com>:
