### ISSUE TITLE
How to run ant swc android package When Change icon in android

### ISSUE THREAD

**Issue by greatpatawee** [marpies/onesignal-ane#19]
Hello 

I already replace icon in folder 

but i don't know how to run ant swc android package for rebuild ane

help pls

Thank you

**Comment by marpies** [comment]
Hi,

You need to download and install [Apache Ant](http://ant.apache.org/bindownload.cgi) and [Gradle v2.14.1](https://gradle.org/releases). After that edit the [build.properties file](https://github.com/marpies/onesignal-ane/blob/master/build/build.properties) and update the paths to AIR SDK and Gradle binary. Then navigate to the `build` folder via command line and run `ant swc android package`.

If it is too difficult for you then you may try [this ANE tool from myflashlabs](http://www.myflashlabs.com/adobe-air-native-extension-resources-project/) to replace the icons inside the [ANE package](https://github.com/marpies/onesignal-ane/releases) available in this repository.

**Comment by greatpatawee** [comment]
Thank you very much marpies, I will try it both
Fast reply
You are very nice person
