### ISSUE TITLE
Add idsAvailable Method

### ISSUE THREAD

**Issue by dnikolaev** [marpies/onesignal-ane#2]
This is really useful method to get user id after the device is successfully registered with OneSignal.

https://documentation.onesignal.com/docs/android-sdk-api#IdsAvailable
https://documentation.onesignal.com/docs/ios-sdk-api#IdsAvailable

**Comment by marpies** [comment]
You can use `OneSignal.addTokenReceivedCallback` to get those ids:

``` as3
OneSignal.addTokenReceivedCallback( onPushTokenReceived );
...
private function onPushTokenReceived( oneSignalUserId:String, pushToken:String ):void {
    if( pushToken != null ) {
        OneSignal.removeTokenReceivedCallback( onPushTokenReceived );
    }
    // 'pushToken' may be null if there's a server or connection error
}
```

**Comment by dnikolaev** [comment]
Hi @marpies,

Thank you for advice. I know it.

But if I need those ids after 'onPushTokenReceived' was dispatched. How I can get them?

**Comment by marpies** [comment]
Hi @dnikolaev,

You'd have to store the ids received in the callback to access them later. If that's inconvenient then I'll add the method.

**Comment by dnikolaev** [comment]
It's inconvenient in some cases. Moreover idsAvailable available at Android/iOS SDK. I think it should be available at AIR SDK too. I'll be glad if you add the method. 😄
