### ISSUE TITLE
Android - ReceivedCallback - Message always ""

### ISSUE THREAD

**Issue by jsaade** [marpies/onesignal-ane#22]
When a push is received, the notification of type OneSignalNotification has the `message `always as empty string.
Everything else seem working fine.

**Comment by jsaade** [comment]
The issue is probably from:
`String message = (payload.groupMessage != null) ? payload.groupMessage : payload.body;
		addValueForKey( json, "message", message );`

Even when I do not specify a group message, it is an empty string and not null, this is why payload.body is never sent to the app.

On iOS it works as the code does not check for groupMessage:
`json[@"message"] = payload.body;`

**Comment by marpies** [comment]
Thanks, the extra conditional should not be there. If you just use the `body` then it'll work fine.

**Comment by leossmith** [comment]
I think i have a similar problem. On android i was using 

`private function onNotificationReceived( notification:OneSignalNotification ):void
			{
                                trace(notification..additionalData.title);
				trace(notification.message);			}`

It used to work but on the last couple of push, the message is empty.

**Comment by marpies** [comment]
Is it empty if the notifications are grouped or does it happen for single notifications as well?

**Comment by leossmith** [comment]
I only use single notifications so I haven't tried grouped. Is there an alternative for single notifications?

EDIT:
Ok so after testing a bit, the message looks like it is empty whatever i send however the if i add a group message then it is received as should. Could t his be a change in OneSignal SDK so the ANE needs update?
