### ISSUE TITLE
(Missing Android Support Library) 	for some devices and (No Push Token) unity sdk

### ISSUE THREAD

**Issue by lucid-dreamm** [marpies/onesignal-ane#24]
Hi.I downloaded the latest unity sdk.I replaced my api key inside the code and press assets/play service resolver/ android .... My package name is correct and it is the same as I created inside the site.
build the sample with gui for android but I see (Missing Android Support Library) for some devices and (No Push Token) inside all users section of my onesignal. the onesignal version is 2.4.0 and unity one is 5.6.0f3
thx.

**Comment by marcoapferegrino** [comment]
any update ?

**Comment by marpies** [comment]
I'm sorry I'm confused. This repository is not meant for Unity, how did you end up here?
