### ISSUE TITLE
ANE crashes on first start of my app

### ISSUE THREAD

**Issue by subdan** [marpies/onesignal-ane#26]
Hello.

When the `OneSignal.init` method called my app crashes. Why it happens? How to fix it? I noticed that my app crashes only one time after I installed the app.

```
public function Main()
{
	addEventListener(Event.ADDED_TO_STAGE, onAddedToStage);
	
	setupStarling();
	
	OneSignal.settings
	         .setAutoRegister(true)
	         .setEnableInAppAlerts(false)
	         .setShowLogs(true);
	
	setTimeout(OneSignal.init, 5000, "487972a0-83f1-4bcb-8de5-9d54e7082769");
	
	OneSignal.idsAvailable(onOneSignalIdsAvailable);
	OneSignal.addNotificationReceivedCallback(onNotificationReceived);
}
```

If I change 5000 ms delay to 10000 ms the app crashes after 10 sec after the first run.

**Comment by marpies** [comment]
Hello,

What system is it crashing on? Did you try to check the device logs? I'm sure there will be some helpful message for you to see.

**Comment by subdan** [comment]
It is crashing only on Android. How can I get Android device logs?

**Comment by subdan** [comment]
Logs:
[a.txt](https://github.com/marpies/onesignal-ane/files/1460390/a.txt)

**Comment by marpies** [comment]
Try to add this to your Android manifest where you list your permissions:

```xml
<uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>
```

**Comment by subdan** [comment]
Thanks! I'll try it on the Monday.

**Comment by marpies** [comment]
Ok, please report back, thank you.

**Comment by subdan** [comment]
I added next permissions and now it doesn't crash. Thanks!

                
                <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE" />
                
                <uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE"/>
                
                <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT"/>
                
                <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>
                <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>
                
                <uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS"/>
                <uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT"/>
                
                <uses-permission android:name="com.sec.android.provider.badge.permission.READ"/>
                <uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>
