### ISSUE TITLE
Update Native SDK (iOS, Android)

### ISSUE THREAD

**Issue by dnikolaev** [marpies/onesignal-ane#27]
Hi Marcel,

Please update native SDK.

https://github.com/OneSignal/OneSignal-Android-SDK
https://github.com/OneSignal/OneSignal-iOS-SDK

Regards,
Dmitrii

**Comment by leossmith** [comment]
+1

**Comment by leossmith** [comment]
Unfortunately the outdated Android SDK started causing crashed on Android O due to the change of handling the background apps. This cannot longer be used with Android version 8.

**Comment by jkasten2** [comment]
@leossmith Until the next updated you can use `targetSdkVersion 25` so your app will run in Android Nougat (7.0) compatibility mode on Android O devices to fix the crash.

Add the following to your `app.xml`
`<uses-sdk android:targetSdkVersion="25"/>`
Example:
```XML
<android>
  <manifestAdditions>
    <![CDATA[
      ...
      <uses-sdk android:targetSdkVersion="25"/>
      ...
   ]]>
  </manifestAdditions>
</android>
```
https://stackoverflow.com/questions/25110326/minsdkversion-google-play-adobe-air

**Comment by leossmith** [comment]
I thought that this would might be a fix :) I will try it, but I already forked this rep and I think that I fixed it for android. I am testing it to figure out if everything is ok after updating to Onesignal 3.6.5. I am also trying to fix the empty message.
