### ISSUE TITLE
Add clearOneSignalNotifications and cancelNotification methods

### ISSUE THREAD

**Issue by dnikolaev** [marpies/onesignal-ane#28]
Hi Marcel,

Please add these methods to the AIR SDK.

Android Native SDK provides both of them: [clearOneSignalNotifications](https://documentation.onesignal.com/docs/android-native-sdk#section--clearonesignalnotifications-) and [cancelNotification](https://documentation.onesignal.com/docs/android-native-sdk#section--cancelnotification-).

iOS Native SDK doesn't provide such methods. So we have to use [UNUserNotificationCenter](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter) methods [removeAllDeliveredNotifications](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649502-removealldeliverednotifications) and [removeDeliveredNotifications](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649500-removedeliverednotifications).

Regards,
Dmitrii

**Comment by marpies** [comment]
I did not add `cancelNotification` method, because currently you can only get the notification id when the notification is tapped. However at that point the notification is removed, thus the method does not seem very practical.
