### ISSUE TITLE
Crashes in Android 8

### ISSUE THREAD

**Issue by noamgat** [marpies/onesignal-ane#30]
After integrating OneSignal, we are seeing a repeat crash in Crashlytics, that only happens in Android 8 devices.

Fatal Exception: java.lang.RuntimeException
Unable to start service com.onesignal.SyncService@cc19a71 with Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=air.com.supermechs.superapp/.AppEntry }: java.lang.IllegalArgumentException: No such service ComponentInfo{air.com.supermechs.superapp/com.onesignal.SyncJobService}

Caused by java.lang.IllegalArgumentException
No such service ComponentInfo{air.com.supermechs.superapp/com.onesignal.SyncJobService}

android.os.Parcel.readException (Parcel.java:1946)
--
  | android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:44)
  | com.onesignal.OneSignalSyncUtils.scheduleSyncTask (OneSignalSyncUtils.java:46)
  | com.onesignal.SyncService.onTaskRemoved (SyncService.java:128)
  | com.onesignal.SyncService.onTaskRemoved (SyncService.java:101)
  | android.app.ActivityThread.handleServiceArgs (ActivityThread.java:3555)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

Reading this thread:
https://github.com/OneSignal/OneSignal-Android-SDK/issues/337
It looks like it is related to adding 
android:permission="android.permission.BIND_JOB_SERVICE"
to the manifest XML.
However, the thread states adding it to NotificationExtender, which isn't defined in the manifest. Perhaps this is due to difference in versions of OneSignal SDKs.
So we don't know where this permission declaration should be placed.
Compiled on Air 24,  min sdk 9, target sdk 24

**Comment by jkasten2** [comment]
@noamgat The error is noting that `com.onesignal.SyncJobService` is missing from the `AndroidManifest.xml`.
```java
Caused by java.lang.IllegalArgumentException
No such service ComponentInfo{air.com.supermechs.superapp/com.onesignal.SyncJobService}
```

This was added in version 3.6.3 of the OneSignal Android native SDK.
https://github.com/OneSignal/OneSignal-Android-SDK/commit/153aecc6f4f1d8e5a4cff0a83ff1c350dfc93d88#diff-42963681f8e299fa36f856450f055e31R72

It looks like this should be add to the readme setup guide to include this.

@marpies I don't know much about how ANE works but does it support Gradle or at least `.aar` libraries?  This way you won't have to maintain any future changes to `AndroidManifest.xml`.

**Comment by noamgat** [comment]
Interesting. The full AndroidManifest.xml you linked to also contains

 service android:name="com.onesignal.NotificationRestoreJobService"
                 android:permission="android.permission.BIND_JOB_SERVICE"

and it adds

android:permission="android.permission.BIND_JOB_SERVICE"

to the GcmIntentService declaration as well

**Comment by marpies** [comment]
@noamgat
Thanks for reporting. I have updated the README guide.

@jkasten2
Thanks for the info. Unfortunately the AndroidManifest is managed manually for each AIR app, so it has to be maintained continuously.

**Comment by noamgat** [comment]
I am not sure about NotificationRestoreJobService. I don't see it in the OneSignalSDK.jar that is in the ANE. @jkasten2 are you sure you pointed to the right version? @marpies which version of the SDK is in the ANE?

**Comment by marpies** [comment]
@noamgat 
The ANE is using version `3.7.1` of the Android SDK. I used the manifest as shown in the [OneSignal Android repo](https://github.com/OneSignal/OneSignal-Android-SDK/blob/153aecc6f4f1d8e5a4cff0a83ff1c350dfc93d88/OneSignalSDK/onesignal/src/main/AndroidManifest.xml), which was last updated on Sep 23, 2017. Perhaps the `NotificationRestoreJobService` was removed?

**Comment by jkasten2** [comment]
@marpies Sad Adobe doesn't support gradle yet.

There were a few other changes in versions in 3.6.4 as well such as the addition of `com.onesignal.RestoreKickoffJobService`.

Also `NotificationRestoreJobService` was renamed to `RestoreJobService` so this is the new class that needs to be in the manifest.

I recommend checking the following 2 URL before releasing an update to ensure nothing has changed by viewing the history.
* https://github.com/OneSignal/OneSignal-Android-SDK/blob/LATEST_VERSION_HERE/OneSignalSDK/onesignal/src/main/AndroidManifest.xml
* https://github.com/OneSignal/OneSignal-Android-SDK/blob/LATEST_VERSION_HERE/OneSignalSDK/onesignal/src/release/AndroidManifest.xml

**Comment by noamgat** [comment]
I can confirm that both RestoreJobService and RestoreKickoffJobService exist in the OneSignalSDK.jar that is part of the ANE

**Comment by marpies** [comment]
@jkasten2 
Thanks a lot for the pointers. I will keep that in mind going forward.

@noamgat 
I have updated the README again.

**Comment by noamgat** [comment]
Great, we are uploading a quick update to our app, will update tomorrow to see if its stable with the manifest changes.

**Comment by noamgat** [comment]
Looks good so far. Thanks @marpies @jkasten2
