### ISSUE TITLE
Action Buttons doesn't work on iOS

### ISSUE THREAD

**Issue by subdan** [marpies/onesignal-ane#31]
Hello. I want to add two action buttons Run and Delay.
I use PHP to send Push notification.

`'buttons' => array(array("id" => "id1", "text" => "Run", "icon" => "ic_menu_share"), array("id"=> "id2", "text"=> "Delay", "icon"> "ic_menu_send"))`

On Android it works well. I see action buttons. But on iOS I don't see the Action Buttons. How to fix this issue?

I noticed that If my app in foreground I see Alert with these buttons but when my app in background mode notification popup doesn't contain action buttons.

**Comment by jkasten2** [comment]
@subdan For iOS this feature requires setting up a Notification Service Extension noted in this guide.
https://documentation.onesignal.com/docs/ios-sdk-setup#section-1-add-notification-service-extension

However I am not sure if this is possible with ANE. @marpies Might have some insight into this though

**Comment by marpies** [comment]
The service extension cannot be built into the ANE. You will need to create the service extension manually yourself, link it against the static library inside the ANE and package it in your AIR app.

**Comment by subdan** [comment]
Thanks!
