### ISSUE TITLE
GDPR additions

### ISSUE THREAD

**Issue by Gratsonia** [marpies/onesignal-ane#34]
Hello.

Could you please add support for additional OneSignal methods for deleting opted-out users' personal data and delaying data collection until user consent is obtained?

As is documented here:
https://documentation.onesignal.com/v5.0/docs/handling-personal-data

Thank you!

**Comment by marpies** [comment]
Hi,

The new APIs are available in [v1.4.0](https://github.com/marpies/onesignal-ane/releases/tag/v1.4.0).
