### ISSUE TITLE
Does it need firebasecore to work on Android?

### ISSUE THREAD

**Issue by leossmith** [marpies/onesignal-ane#35]
I added the new version to a new app and it doesn't seem to even register the device in the Onesignal panel.

However if i use the same app id and sender id on another App that uses firebase, everything works as expected.

**Comment by marpies** [comment]
Sorry for the late reply.

That's strange, I'm not including Firebase in my test app and it works correctly. Do you have the necessary Play Services ANEs in your project?

**Comment by leossmith** [comment]
Yup, I can't figure what is happening. I can see that Distriqt also added on their documentation that Onesignal needs firebase. It works perfectly on all my projects which also use Firebase, but not in clean projects.

**Comment by jkasten2** [comment]
@marpies @leossmith OneSignal will use either the GCM or Firebase library depending on what is available at runtime in your app. In the future GCM support will be dropped from the OneSignal SDK, however this won't happen for 6+ months.
