### ISSUE TITLE
Conflict on included ANE files and pushToken getting Null

### ISSUE THREAD

**Issue by mtilhan** [marpies/onesignal-ane#36]
I am using this ANE with GoogleSignIn-Ane.
https://github.com/myflashlab/GoogleSignIn-ANE

I allready added this dependency extensions in my project;
com.google.android.gms.base (googlePlayServices_base.ane)
com.google.android.gms.basement (googlePlayServices_basement.ane)
from: https://github.com/myflashlab/common-dependencies-ANE/tree/master/googlePlayServices

Then pushToken gets always null. But if i replace those with yours i am getting Token without problem;
com.marpies.ane.googleplayservices.base.ane	
com.marpies.ane.googleplayservices.basement.ane

In the documentation says there is no need to add them unless you already added but not working in this case. If i added both extensions i am getting conflict error too. So is there a way to work both ANE without problem?

**Comment by marpies** [comment]
It seems to work correctly when I use the following setup:

```xml
<extensionID>com.marpies.ane.onesignal</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.analytics</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.analytics.impl</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.location</extensionID>
```

**Comment by mtilhan** [comment]
When i used all dependencies from myflashlab its works just like you said. Thanks for the quick response and great work.
