### ISSUE TITLE
GCM Library detected, please upgrade to Firebase FCM library as GCM is deprecated!

### ISSUE THREAD

**Issue by AlexUrrutia** [marpies/onesignal-ane#37]
Hello Marpies, I'm getting this: `W/OneSignal: GCM Library detected, please upgrade to Firebase FCM library as GCM is deprecated!`

How can we compile FCM instead GCM?

**Comment by AngeloLazzari** [comment]
Hi, you have to delete the dependencies from GCM Library and add the new Firebase FCM. you can get info here https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=vswin
