### ISSUE TITLE
deleteTag/deleteTags not working

### ISSUE THREAD

**Issue by chrisDK1977** [marpies/onesignal-ane#44]
I added a tag:
OneSignal.sendTags({date:new Date().toUTCString(), blubber: "something"});

and deleted it in another session by 
OneSignal.deleteTags( new <String>["blubber"] );

But in the One Signal Administration I still see :
{date: Sun Apr 14 10:38:30 2019 UTC, blubber: something}

**Comment by chrisDK1977** [comment]
I am not sure why but now it is working - maybe One Signal needs (a lot of) time to update...?

**Comment by chrisDK1977** [comment]
It seems like setting a tag always works immediately … deleting or updating seems not to work reliable.

**Comment by marpies** [comment]
There is a slight delay before the request is sent to the server. I added a callback to the APIs which tells you when the request has finished.
