### ISSUE TITLE
Android 64 bit support?

### ISSUE THREAD

**Issue by noamgat** [marpies/onesignal-ane#49]
With the upcoming Android deprecation (apps released / updates submitted on august 1 2019 or later in google play store must support 64 bit), is it possible to provide a compilation of this ANE with support for android 64 bit?

**Comment by mtilhan** [comment]
Same question here. Google extended this period until August 2020, but the same need remains. 
Are there any updates planned?

**Comment by marpies** [comment]
Will have a look at this, thanks for the reminder.
