### ISSUE TITLE
Missing Android Support Library

### ISSUE THREAD

**Issue by giaoban** [marpies/onesignal-ane#5]
when i call OneSignal.init(""), tag Subscribed in onesignal.com is (Missing Android Support Library), plz help me

**Comment by dnikolaev** [comment]
Hi @giaoban,

Please read carefully [Getting starting – Additions to AIR descriptor](https://github.com/marpies/onesignal-ane#additions-to-air-descriptor)

If you are targeting Android, add the following extensions from [this repository](https://github.com/marpies/android-dependency-anes) as well (unless you know these libraries are included by some other extensions):

```
<extensions>
    <extensionID>com.marpies.ane.androidsupport</extensionID>
    <extensionID>com.marpies.ane.googleplayservices.iid</extensionID>
    <extensionID>com.marpies.ane.googleplayservices.gcm</extensionID>
    <extensionID>com.marpies.ane.googleplayservices.analytics</extensionID>
    <extensionID>com.marpies.ane.googleplayservices.location</extensionID>
    <extensionID>com.marpies.ane.googleplayservices.base</extensionID>
    <extensionID>com.marpies.ane.googleplayservices.basement</extensionID>
</extensions>
```
