### ISSUE TITLE
problem with ane64bit

### ISSUE THREAD

**Issue by mymishagithub** [marpies/onesignal-ane#51]
hi
first , thanks for updating ANE.

i publish my apk to 32bit and every thing is Ok.
but when i publish to 64bit and make apk.
 SUBSCRIBED cell in onesignal panel->users 👍   show "**Missing Google Play Services Library**"

how can i fix this problem?

thanks

**Comment by marpies** [comment]
Try to [redownload the messaging ANE](https://github.com/marpies/onesignal-ane/releases/download/v1.7.0/com.marpies.ane.firebase.messaging.ane).

**Comment by mymishagithub** [comment]
thanks,my bro.
this ANE fix my problem

 be Cheers.
