### ISSUE TITLE
AndroidX Support / Missing Android Support Library

### ISSUE THREAD

**Issue by mtilhan** [marpies/onesignal-ane#53]
Hello,

When I update dependent libraries to AndroidX, I get "missing android support library" error for Android users in OneSignal panel.

Readme says "com.distriqt.androidsupport.V4" should be added, but the distriqt libraries have switched to AndroidX and i added "androidx.core". Could this be the source of the problem? Or an error may have occurred in firebase libraries due to updates? (I'm using myflashlabs FirebaseAnalytics.ane and its uses (dependency.firebase.messaging-V20.2.3.ane)

By the way, the user seems to be registering but can't get any notification. In OneSignal panel, users look like the following
![dsc](https://user-images.githubusercontent.com/2861152/96367181-d564a500-1154-11eb-8892-f0dd13baed19.JPG)

Development environment:
AIR: 33.1.1.259
OS: Win10 x64
IDE: Adobe Animate 20

**Comment by mtilhan** [comment]
Hello again,

I have a few more findings and I think the error may be related to the firebase version.

When I look at the code
I see you are using "firebase-messaging-17.3.4". It uses "firebase-core-16.0.0.jar" and other 16.0.0 version libraries in "com.marpies.ane.firebase.base.ane". The firebase.core library that I use requires 17. * versions and uses v20.2.3 as the messaging library. I tried different variations of the two libraries and the error persists. I think the problem here is due to the incompatibility of the old firebase libraries.

As a result, I can ask my question as follows; Are you planning to update this ANE project with the current OneSignal and Firebase libraries? : )

Thank you for your work and support.

Regards

**Comment by marpies** [comment]
[v1.8.0](https://github.com/marpies/onesignal-ane/releases/tag/v1.8.0) supports newer Firebase libraries and AndroidX. It should be compatible with myflashlabs dependencies as well.
