### ISSUE TITLE
ShortcutBadger 

### ISSUE THREAD

**Issue by vm2-mobile-devs** [marpies/onesignal-ane#6]
Hi,

I saw that in your Android Manifest file (at the instructions page) you defined some permissions to use the
"ShortcutBadger", if i add those permissions into my manifest, the icon badge on my device will be updated? or do i need to use the ShortcutBadger library? if so, do you have an ShortcutBadger ANE? 

Thanks.

**Comment by marpies** [comment]
Hi @vm2-mobile-devs,

The shortcut badger is part of the OneSignal SDK, you should not need to add anything else to your app to make it work. Is there a problem with this?
