### ISSUE TITLE
Missing Documentation - Notification received and open handler 

### ISSUE THREAD

**Issue by jkasten2** [marpies/onesignal-ane#9]
There is a [`onStatus`](https://github.com/marpies/onesignal-ane/blob/master/actionscript/src/com/marpies/ane/onesignal/OneSignal.as#L481) function in `OneSignal.as` however it is not documented in the [`README.MD`](https://github.com/marpies/onesignal-ane/blob/master/README.md). Include information on how to setup one and read the notification from the [`NOTIFICATION_RECEIVED`](https://github.com/marpies/onesignal-ane/blob/master/actionscript/src/com/marpies/ane/onesignal/OneSignal.as#L495) event as well.

**Comment by marpies** [comment]
Hi @jkasten2,

The `onStatus` method is meant for internal use only and should not be exposed to the developers. The same applies for the `NOTIFICATION_RECEIVED` event. The event is used to receive a message from the native library. The message is parsed by the ActionScript library and `OneSignalNotification` object is created. This object can be retrieved by the developers using a [notification callback](https://github.com/marpies/onesignal-ane#callbacks).
